### ISSUE TITLE
Issue de teste eafflw

### ISSUE THREAD

**Issue by cytryn** [dojoapps/presentation-saidacerta#1]

**Comment by vicentedealencar** [comment]
boa, agora fecha pra ver se funfa

**Comment by cytryn** [comment]
não consigoooo!

**Comment by vicentedealencar** [comment]
serio?

**Comment by cytryn** [comment]
pelo waffle não rolou

**Comment by vicentedealencar** [comment]
hmmmm, nao sabia que era isso que vc tava testando...

interessante, mas pra isso funcionar perfeito eles tem que reimplementar o github inteiro....

achei esse aqui parecido com um approach diferente, se liga: https://www.zenhub.io/

**Comment by vicentedealencar** [comment]
da pra abrir e fechar com drag&drop cool cool cool

**Comment by cytryn** [comment]
Lol, drag and drop não funcionou aqui pra mim.
